### PR TITLE
this is my last commits

### PR DESCRIPTION
**Pull request by pkoutsos**

### CODE REVIEW

**Comment by SoltauFintel** [comment]
files .idea/.name to .idea/vcs.xml not okay in PR

**Comment by SoltauFintel** [comment]
Info: I continued development. It will be more difficult to incorporate your changes. But not impossible. ;-)

**Comment by pkoutsos** [comment]
You do not have to change a lot of things because I have two extra classes, two extra strings.xml, and one more XML file for select language.

**Comment by pkoutsos** [comment]
Also, I forgot the changes to AndroindManifest.xml in order to play first the class SelectLanguage and to change the language and after the class Game.

**Comment by SoltauFintel** [comment]
Unfortunately, you failed with PR. I will now try to apply your changes file by file.

**Comment by SoltauFintel** [comment]
what a shit :-(

**Comment by pkoutsos** [comment]
Do you want me to do something else or you will apply my changes file by file?

**Comment by SoltauFintel** [comment]
Your PR is rejected.

English/German texts are now selected automatically.

**Pull request closed without merging**
