### PR TITLE
strings.xml (en)

### PR DESCRIPTION
**Pull request by pkoutsos**
Hello, I am a student of informatics and I try to improve my programming skills, I like your game and I have made an English version also. I want to upload my files and i will like to take your feedback.

### CODE REVIEW

**Comment by SoltauFintel** [comment]
Thank you, great! It looks like you have replaced the German texts by the English texts. But both languages should exist at the same time. I don't know how to do it myself. Is my first Android app. The language should be selected automatically by the device. I guess Android does this automatically.

**Comment by pkoutsos** [comment]
I have done a version with both german and English , but i need your permission in order to upload my files and to see my changes.

**Comment by SoltauFintel** [comment]
I cannot see your changes in Your repo. https://github.com/pkoutsos/blockpuzzle/commits/patch-1

step 1: Please push all your changes to **Your** repo in **Your** branch patch-1. You can check that with the above URL.

step 2: The PR in my repo must be updated. I don't know if that happens automatically or if someone has to do something.

**Comment by pkoutsos** [comment]
I commit my version of your project i hope i have done it right

**Comment by SoltauFintel** [comment]
Phew, that doesn't look good. In your master commit https://github.com/pkoutsos/blockpuzzle/commit/a3cd8c88e0b1b7e8f9eb914fb5f5727f304f5ccf you can see that you (apparently) changed a lot of files. That makes checking your changes difficult for me.

You kind of re-added the blockpuzzle-master folder. As a result, files are now duplicated in your repository.

Basically I am ready to accept your changes, but not in this state.

My advice: back up your changed files. Delete your forked repository on Github and on your computer. Start over. Fork my repo and create a new branch. Etc.

**Comment by pkoutsos** [comment]
I have not done a lot of commits and this is the reason that I make mistakes.

**Comment by pkoutsos** [comment]
I have deleted the blockpuzzle-master folder from my repository and I have done two extra commits. One with only my new files and the second one the new files into yours. I hope it is ok.

**Comment by SoltauFintel** [comment]
In Germany we say: "No master has fallen from the sky yet." and "Practice creates masters."

Maybe YouTube videos will help. If you do this properly, I'll apply your changes. 😃

**Comment by SoltauFintel** [comment]
> I have deleted the blockpuzzle-master folder from my repository and I have done two extra commits. One with only my new files and the second one the new files into yours. I hope it is ok.

let me have a look...

**Comment by SoltauFintel** [comment]
Please raise a new PR and then check if only your changes are listed.

**Comment by SoltauFintel** [comment]
Do you know how to raise the new PR?

After you have raised the PR I will comment your code changes. ;-)

**Pull request closed without merging**
